auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:categories/:title

excerpt_separator: <!--more-->

# global vars
title: URL2io
url: blog.url2io.com

# components
CP: 
  # setting comments
  comments:
    provider: duoshuo
    duoshuo:
      short_name: url2io
